### ISSUE TITLE
Update wiki with M2 deliverables

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#140]
# Update Wiki with M2 Deliverables Information

## Description:
Update the wiki with M2 deliverables, including links to relevant resources (Figma, architecture diagrams) and key details.

## Done:
- **Functional Requirements:** Provide clear, structured info on M2 deliverables, with working links.
- **Quality Standards:** Follow project documentation style, ensure clarity, and check all links.
- **Testing Requirements:** No formal tests, ensure links work and page is accessible.

## Preconditions:
- M2 deliverables and resources must be finalized.
- Wiki access for updates.

## Steps to Completion:
- [ ] Gather M2 deliverables info and links.
- [ ] Structure and update the wiki.
- [ ] Verify all links and publish.

## Points to Consider / Known Risks:
- Ensure resources are up to date.
- Avoid broken links or unclear formatting.

**Comment by francelu** [comment]
[Here](https://github.com/PeriodPals/periodpals/wiki/Milestones#milestone-2)'s the link to what I've written in the wiki for the M2 so we stay organised.

**Comment by charliemangano** [comment]
LGTM! Thanks for all the work!
