### ISSUE TITLE
Step 5: Add a wiki page for directives about padding and typography.

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#141]
Add directives for padding and typography in wiki. Subtask from #82.

**Comment by francelu** [comment]
Need to update the wiki pages at the end of #82 with the new dimension in `Dimens.kt`, new typographies in `Type.kt`.

**Comment by francelu** [comment]
Updated. Find the new guidelines [here](https://github.com/PeriodPals/periodpals/wiki/App-Style-Guide#general-padding-and-typography).

**Comment by taghizadlaura** [comment]
It seems well documented! Thank you for your work!
