### ISSUE TITLE
Create a loading screen between profile creation and profile view 

### ISSUE THREAD

**Issue by Harrish92** [PeriodPals/periodpals#156]
### Description:
The task involves implementing the `LoadInitialData` composable function to handle the initial data loading process in the application. This function will display a loading indicator while data is being fetched and navigate to the profile screen once the data is loaded.

### Done:
Specific, measurable criteria to confirm the task is complete.
- **Functional Requirements:**
- Implement the `LoadInitialData` composable function.
- Display a loading indicator (`CircularProgressIndicator`) while data is being fetched.
- Navigate to the profile screen (`Screen.PROFILE`) once the data is loaded.
- **Quality Standards:**
- Code should follow the project's coding standards and guidelines.
- **Testing Requirements:**
- Write UI tests for `LoadingScreen` to verify the elements are displayed correctly.
- Write unit tests to verify the navigation functionality.
- Ensure code coverage targets are met for the new function.

### Steps to Completion:
Break down the task into actionable steps. Make sure those steps are separable so that you can easily create subtasks/subissues from these:
- [x] Create the `LoadInitialData` composable function.
- [x] Implement the loading indicator using `CircularProgressIndicator`.
- [x] Implement the navigation to the profile screen upon data load completion.
- [ ] Write UI tests for `LoadingScreen` to verify the elements are displayed correctly.
- [x] Write unit tests for the navigation functionality.

**Comment by charliemangano** [comment]
As we are gonna be using this loading screen between more screens than just CreateProfile and Profile, we need to make it usable everywhere. Updating the description accordingly and creating different tasks to integrate it between CreateProfile and Profile, and between SignIn/SignUp and CreateProfile.

**Comment by charliemangano** [comment]
Fixed by #190

**Comment by francelu** [comment]
Won't fix. Found another way.
