### ISSUE TITLE
Fix secrets not properly applied in CI build apk

### ISSUE THREAD

**Issue by charliemangano** [PeriodPals/periodpals#161]
### Description:
At the moment, the authentication screens fail when trying to log in or sign up on the build apk. The goal of this task is to look into what's causing this problem and fix it. This bug seems to be entirely unrelated to the syncing problem we noticed during Sprint 4.

**Steps to reproduce:**
 - push your branch (`main` in this case) to a `build/*` branch. This will run the CI that builds our apk.
 - download the apk and install on your device (take care to uninstall any previous versions of the app if you already have it install, and to clean the caches)
 - launch the app and (correctly) fill the fields on either the SignIn or SignUp screen
 - click on submit button ("Sign In" or "Sign Up")

**Expected (buggy) behaviour:**
A toast should appear explaining that the authentication failed, and you will not navigate to the next screen (create profile or profile).

### Done:
- authentication must be possible thought the build apk, with leniency for the syncing bug
- code quality should be conform to our standards and consistent with the rest of the app
- testing: user tests (download the apk on multiple devices and test that it works)

**Comment by charliemangano** [comment]
The logcat show this trace (abridged):

```console
Supabase-Core E : POST request to endpoint /auth/v1/signup failed with exception Unable to resolve host "null": No address associated with hostname
AuthenticationModelSupabase D : register: failed to register the user: HTTP request to https://null/auth/v1/signup (POST) failed with message: Unable to resolve host "null": No address associated with hostname
AuthenticationViewModel D : signUpWithEmail: failed to register user: io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to https://null/auth/v1/signup (POST) failed with message: Unable to resolve host "null": No address associated with hostname
```

It seems to be a problem with either network connection or Supabase URL not being fetched correctly from `BuildConfig`

**Comment by charliemangano** [comment]
The network connection is alright, I fixed it right after M1. The problem comes form the CI not having access to the necessary API keys and client URLs. Those are stored in `local.properties` and then piped to `BuildConfig` during the build. 

However, `local.properties` is a file that should never be pushed to VCS, and therefore is not accessible by the CI pipeline during its build. They are therefore not piped to `BuildConfig` when the CI builds, but are when building on local, which makes the problem really annoying to detect and to fix :(

**Comment by francelu** [comment]
Good job find a way to solve this issue !  
It's good you commented here your researches and findings :)
