### ISSUE TITLE
Model and ViewModel for Alerts: list of tasks 

### ISSUE THREAD

**Issue by agonzalez-r** [PeriodPals/periodpals#17]
* [x] #133
* [x] #117
* [x] #118 
* [x] #120
* [x] #119

**Comment by lazarinibruno** [comment]
**Done:** 
* We implemented the alert data class.
* We defined the functions in the interface to interact with the database. 

**TODO:**
* Implement the Model functions to interact with the data in the supabase db.
* Implement the ViewModel to link the data with the AlertScreen and AlertListScreen.

**Comment by charliemangano** [comment]
Nice work!
Can you link the branch where you did this work to this issue? (on the right side, under Development, click on the setting button)

**Comment by lazarinibruno** [comment]
Done!
