### ISSUE TITLE
Update Figma to reflect changes to the app

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#198]
Update Figma with the changes and ideas.

See [this](https://github.com/PeriodPals/periodpals/pull/183#issue-2652493769) and this [PR](https://github.com/PeriodPals/periodpals/pull/194).

**Comment by francelu** [comment]
Updated the necessary changes [here](https://www.figma.com/team_invite/redeem/MnyBeEvw4fKH4aV5aVBpPb).  

Please give feedback devs :)

**Comment by coaguila** [comment]
lgtm thank you very much

**Comment by charliemangano** [comment]
Up to date with the app and looks very nice! Thanks for the work!
LGTM
