### ISSUE TITLE
Research StreamSDK

### ISSUE THREAD

**Issue by taghizadlaura** [PeriodPals/periodpals#246]
## Description  
Research the functionality and operation of StreamSDK specifically for implementing a real-time chat feature. The goal is to understand how the SDK works, its requirements, and its integration process, enabling future development of a chat system within the project. This task focuses on gathering the necessary knowledge to implement a robust and scalable chat solution.  

## Done  

- **Functional Requirements:**  
  - Gain a detailed understanding of StreamSDK’s chat-specific features and APIs.  
  - Identify steps for integrating StreamSDK for a chat implementation.  
  - Document use cases, limitations, and any customizations required for the project.  

- **Quality Standards:**  
  - Ensure the research provides clear and actionable guidance for implementation.  
  - Verify that the SDK meets project standards for performance, scalability, and security.  

- **Testing Requirements:**  
  - Outline a plan for testing chat functionality after implementation, including edge cases and performance scenarios.  

## Preconditions  

- Access to StreamSDK documentation, API keys, and chat-related examples.  
- Familiarity with the project’s requirements for a chat system, including design and user expectations.  
- Knowledge of the project’s architecture and constraints that may affect chat integration.  

## Steps to Completion  

- [x] Review StreamSDK documentation with a focus on chat-specific features.  
- [x] Explore StreamSDK’s sample projects and demos for chat integration.  
- [ ] Identify the necessary setup, such as authentication and backend configuration. : In progress

## Points to Consider / Known Risks  

- Some advanced chat features may require a subscription or additional resources.  
- The implementation timeline may be impacted by constraints in project architecture or dependencies.  
- Real-time messaging performance depends on external API reliability and network conditions.

**Comment by francelu** [comment]
- I also checked a gitHub [repository](https://github.com/Assocify-Team/Assocify) from which I couldn't understand a lot.
- Beside Laura's proposed [turorial](https://getstream.io/tutorials/android-chat/#client-setup), I had a look at another [tutorial](https://getstream.io/tutorials/kotlin-chat/) which uses `viewBinding` but we don't...
- On YouTube, I looked up for tutorial videos. I found this series : 
  - Build a Chat App using Stream Chat SDK for Android | [Part #1](https://www.youtube.com/watch?v=GrAwH6Sb834)
  - Build a Chat App using Stream Chat SDK for Android | [Part #2](https://www.youtube.com/watch?v=OlbBcclGPK8)
  - Build a Chat App using Stream Chat SDK for Android | [Part #3](https://www.youtube.com/watch?v=GKOrG-bvPWo)
  Which leads you back to the same [GitHub repository](https://github.com/GetStream/stream-chat-android) as the website tutorial's link's GitHubRepository.
