### ISSUE TITLE
Update Figma to have presentable flows and wireframes

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#34]
From the M1 handout:

> We suggest that you start with wireframes, and then create full mockups whose screens are linked together, so that you can test out the user flow and build a shared understanding within your team of what the application should look like. This will make it easier to define clear development tasks.
> 
> For the M1 deliverable, create a named version called "M1" on figma.com, copy the link from the version history, and put it in your wiki. Make sure the Figma is accessible to everyone.

**Comment by francelu** [comment]
We should think about the way we want to implement the user's age on the profile screen.  
![image](https://github.com/user-attachments/assets/5b248795-d1aa-4854-a0cf-6baefe8d7d86)

**Comment by francelu** [comment]
There might be a way to display error messages of `OutlinedTextFields` as in the Figma material3 (see below).  
Might be better than our current version with our own `ErrorText` component.
![image](https://github.com/user-attachments/assets/352b6303-f022-4dc4-a0ec-5809fe83ddf8)

**Comment by francelu** [comment]
We should consider changing asap the bottom navigation bar, at least put "Alert" in the middle :  
![image](https://github.com/user-attachments/assets/bedb7f7c-bfe6-4263-8fe4-679841e969dc)

**Comment by taghizadlaura** [comment]
I have reviewed all the Figma designs, including the wireframe and the mockup, and I didn't find any problematic points! You have done a really great job! Your attention to detail is impressive, and the overall layout is intuitive and user-friendly. I appreciate the effort you've put into this; it really enhances the project!

**Comment by francelu** [comment]
Figma is done. Here's the [link](https://www.figma.com/design/r6jgyWnwTQ6e5X1eLpeHwN/PeriodsPals?version-id=6879707394&node-id=0-1&node-type=canvas&t=GUcTiDq4oI7jouPi-0).  
@agonzalez-r Thanks for doing the wireframes !!  
@lazarinibruno Thanks for the draft of `ListScreen` and its list items :)
