### ISSUE TITLE
Implement auth sign-in and sign-up screens (UI)

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#4]
As a user, I want to sign-up or login to my account so that my preferences are kept across devices.

**Comment by agonzalez-r** [comment]
Create Authentication Screen with sign-in/log-in button

**Comment by francelu** [comment]
Here is a preview of the screen without having implemented Supabase yet.
Awaiting pull-up request reviews.
![image](https://github.com/user-attachments/assets/459af78a-6a5a-4d73-8eaa-6ab3eba7ab28)

**Comment by francelu** [comment]
Sign-in and Sign-up screens are implemented. 
Awaiting for navigation and Supabase :) 
I've added a feature of checking for password containing at least one capital character, one small character, one number, and one special character. It displays on the screen when these conditions aren't satisfied.

### Sign-up screen

<img src="https://github.com/user-attachments/assets/1a40aa2e-d2eb-4783-93ba-938493e486dc" width="200" /> 
<img src="https://github.com/user-attachments/assets/28463985-9cf1-4bb5-9111-96cebde1d3ea" width="200" /> 
<img src="https://github.com/user-attachments/assets/34125e1a-9dac-4a71-9150-0f9045a91b30" width="200" /> 
<img src="https://github.com/user-attachments/assets/80cc80f6-5dcb-4127-b3d8-26b5f37b5bcb" width="200" /> 

<img src="https://github.com/user-attachments/assets/dc6f6c79-8acb-4ef1-a87f-0cc260ba506b" width="200" /> 
<img src="https://github.com/user-attachments/assets/304765f2-99f7-4966-acde-8fc3b2f506fc" width="200" /> 
<img src="https://github.com/user-attachments/assets/63e2be48-dc2c-4cdb-9d14-7168397a0954" width="200" /> 
<img src="https://github.com/user-attachments/assets/7b47655e-57cd-4b58-b40b-f65453ba1c3c" width="200" />

### Sign-in screen

<img src="https://github.com/user-attachments/assets/f32592f4-b2e2-4088-aa4f-2ee191167f89" width="200" /> 
<img src="https://github.com/user-attachments/assets/ed50b806-1e9f-4ec7-850b-097d0ac46b23" width="200" /> 
<img src="https://github.com/user-attachments/assets/661a7ebf-88af-4b75-9779-1a2eb6d04174" width="200" /> 
<img src="https://github.com/user-attachments/assets/84d1f417-504f-45a1-9a92-eebffe6c5424" width="200" />

**Comment by charliemangano** [comment]
next time separate this into two different tasks (sign in and sign up)

**Comment by francelu** [comment]
Here's a preview of the Sign-In screen:  
![image](https://github.com/user-attachments/assets/b8cdf324-e114-4b6f-9ae0-e51632f6a2cf)
