### ISSUE TITLE
Integrate navigation into all screens

### ISSUE THREAD

**Issue by agonzalez-r** [PeriodPals/periodpals#42]
Add Top Bar and Bottom Navigation Menu to all the Screens 
+ back button to the Edit Profile Screen

**Comment by lazarinibruno** [comment]
We were trying to use Mockito to mock the NavHostController and the NavigationDestinations in the end-to-end test. However, we realized (a bit to late) that in such tests, nothing should be mocked. The purpose of Mocking is to isolate the behavior of individual classes (for instance, the navigationActions class). It helps avoiding side-effects of dependencies. Thus, it should only be used in unit testing.

E2E tests are meant to test the entire flow of the application, from the UI to the backend. So we should use the actual classes and dependencies without mocking anything.
