### ISSUE TITLE
Define basic UI and design figma

### ISSUE THREAD

**Issue by taghizadlaura** [PeriodPals/periodpals#5]
Define main screens and navigation routes, as well as basic Figma wireframes

**Comment by taghizadlaura** [comment]
[Drive to the first UI design](https://drive.google.com/drive/folders/1ewvXzQO8nI4KSf0wif6TV9V1SGt8ofhF?usp=drive_link)

**Comment by agonzalez-r** [comment]
Screens to design on Figma: 
- Auth screen
- Create Profile screen
- Overview (menu) screen 
- Request Help screen 
- Offer Help screen
