### ISSUE TITLE
Fix UI tests for M1

### ISSUE THREAD

**Issue by charliemangano** [PeriodPals/periodpals#63]
Fix and clean up UI tests for the files submitted for M1. Add missing tests.

### Done
* [x] UI tests complete for all the screens:
  * [x] Alert (#64, #68)
  * [x] AlertList (#69, #70)
  * [x] SignIn (#71, #73)
  * [x] SignUp (#76, #96)
  * [x] CreateProfile (#74)
  * [x] Profile (#83)
* [x] UI tests complete for all the navigation components:
  * [x] BottomNavigationMenu (#97, #105)
  * [x] TopAppBar (#90, #91)
* [x] Line coverage is > 80%

Map : We decided to complete the tests when the task "Change Map to Maplib" will be done
MainActivity (#86) : We decided to do not fix it for this week since the existing tests were about the Location which will be moved in another file

**Comment by agonzalez-r** [comment]
First step: 

Get Mockito to work for Android Tests in order to mock navigationActions

**Comment by francelu** [comment]
Hey, in #66 I'm checking the onClick actions. Don't bother too much about this part since I'll be writing tests for that specific part too. Mainly `CreateProfileScreen` and `CreateAlertScreen`.
