### ISSUE TITLE
Make layout responsive to all screen orientations

### ISSUE THREAD

**Issue by taghizadlaura** [PeriodPals/periodpals#75]
### **Description:**
Even if the task is called "Make layout responsive to all screen orientations", we will only focus for this task sprint on blocking the screen orientation to "portrait" mode.

### **Acceptance Criteria:**
Specific, measurable criteria to confirm the task is complete.
- **Functional Requirements:** The screen is blocked in "portrait" mode even if you turn the phone.
- **Quality Standards:** Ensure it only use essential code that requires minimal changes in the future to ensure it remains efficient and maintainable.
- **Testing Requirements:** Ensure >=80% code coverage.

### **Preconditions:**  
- Access to the latest version of Android Studio and the project repository.
- Familiarity with Android manifest configurations and activity lifecycle management.

### **Steps to Completion:**
Break down the task into actionable steps to guide work progression and ensure alignment with the sprint plan:
- [x] **Step 1:** Modify the AndroidManifest.xml to set the screen orientation to "portrait" for the desired activities.
- [x] **Step 2:** Test manually the changes
- [x] **Step 3:** Review code for efficiency and maintainability, ensuring minimal essential code is used.

### **Points to Consider / Known Risks:**  
- **Potential Risks:** User experience may be negatively impacted on devices primarily used in landscape mode.
- **Technical Constraints:** Limited testing on various device sizes and configurations may affect orientation behavior.
- **Dependencies:** May require updates to the UI layout to ensure proper functionality in portrait mode only.

**Comment by francelu** [comment]
Here is the feedback from the M1:
```markdown
## UI

We checked whether the elements of your app's UI are consistent (fonts, colors, etc.) and whether the layout is responsive (i.e., adapts to different screen sizes and orientations).

It does not seem to fit all screen orientations (you can block it otherwise to portait), and the dark mode makes texts less readable.

For this part, you received 3 points out of a maximum of 5.
```  

We will go with blocking the screen to portrait view. Less work, don't see why landscape mode would be good for user experience.

**Comment by francelu** [comment]
I see you've already done a first step. If you've created a branch, please link it to this issue, would be very much appreciated. Thanks ! PO :)

**Comment by taghizadlaura** [comment]
I linked a branch to this issue, but I had to rename it, and now the issue is linked to a non-existent branch since it didn't detect the changes. Does anyone have any ideas on how I can solve this problem?

**Comment by taghizadlaura** [comment]
I found how to do it.
