### ISSUE TITLE
Fix UI tests for M1: MainActivity

### ISSUE THREAD

**Issue by agonzalez-r** [PeriodPals/periodpals#86]

**Comment by agonzalez-r** [comment]
@charliemangano just to make sure, we agreed yesterday during the SM to close this issue, since you were going to remove the tests for MainActivity (because there is nothing to test) during clean up.

**Comment by charliemangano** [comment]
Yes, that's what we agreed to. You can close this issue as not planned (see image)
![image](https://github.com/user-attachments/assets/5c2b0b89-fead-4a9d-a486-1e8adc116fe1)
and add the label "won't fix".
