### ISSUE TITLE
Set up navigation actions, bottom navigation menu, top app bar

### ISSUE THREAD

**Issue by francelu** [PeriodPals/periodpals#9]

**Comment by francelu** [comment]
Should be done.  
Awaiting for Supabase merge.  
Then make a pull-request.

**Comment by francelu** [comment]
We decided to make a bottom nagivation menu.  
Do we still want a top app bar ? So that if we display it on a certain screen, it is standardised for all of them.

**Comment by taghizadlaura** [comment]
I think it's a good idea to keep it for the name of the screens yes.

**Comment by francelu** [comment]
Here's a first preview of the bottom navigation bar :  
![image](https://github.com/user-attachments/assets/93971bea-34bf-46d0-bf16-d897a581df2e)

**Comment by charliemangano** [comment]
I think we can go with this:)
Maybe have the Alert icon be an Outlined icon and not a Filled one for consistency?
![Outlined Warning icon](https://github.com/user-attachments/assets/3a305ace-69c3-4236-83da-780ed947fee1)
and not 
![Filled Warning icon](https://github.com/user-attachments/assets/1e9a9b73-6dec-481a-91b0-3b86ddecd099)

**Comment by francelu** [comment]
Alright, I've changed the icon.  
  
Also, I've noticed coding that the "Notifications" has little troubles to display sometimes due to its length. 
We might need to find another text to display ; maybe just put list icon displaying "List" below it.  
  
Here's a preview of the bottom bar and top bar :  
![image](https://github.com/user-attachments/assets/4e987fd1-7b66-4aa8-93e0-47f998283db1)
